name: afsy

type: php:8.0

runtime:
    extensions:
        - apcu
        - mbstring


build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 1024

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

crons:
    snapshot:
        # everyday at 5AM
        spec: 0 5 * * *
        cmd: |
            # only snapshot the master environment, aka production
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape symfony env:snapshot:create --no-wait
            fi
    renewcert:
        # Force a redeploy at 10 am (UTC) on the 1st and 15th of every month.
        # for the master branch, aka production
        spec: '0 10 1,15 * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape symfony redeploy --no-wait
            fi

relationships:
    database: "database:mysql"
