homepage:
    path:  /
    controller: 'Afsy\Controller\BlogController:index'
    methods: GET

# HWI OAauth
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

# Sensio connect OAauth
sensio_connect_login:
    path: /login/check-connect

logout:
    path: /logout
    methods: GET

# Site / Admin
app:
    resource: '../src/Controller/'
    type: annotation

app_avent:
    resource: '../src/Avent/AdventCalendarController.php'
    type: annotation

admin_redirect:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: false

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
