# HWI OAauth
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

# Sensio connect OAauth
sensio_connect_login:
    path: /login/check-connect

logout:
    path:   /logout

homepage:
    path:  /
    defaults: { _controller: Afsy\Controller\BlogController::indexAction }

feed_atom:
    path: /feed.atom
    defaults: { _controller: Afsy\Controller\BlogController::feedAction }

blog_home:
    path: /blog
    defaults: { _controller: Afsy\Controller\BlogController::indexAction }

blog_show:
    path: /blog/{slug}
    defaults: { _controller: Afsy\Controller\BlogController::showAction }

blog_preview:
    path: /blog/preview/{slug}
    defaults: { _controller: Afsy\Controller\BlogController::showAction, preview: true }

blog_show_tag:
    path: /blog/tag/{name}
    defaults: { _controller: Afsy\Controller\BlogController::showTagAction }

avent:
    path: /avent/{year}
    defaults: { _controller: Afsy\Controller\AventController::indexAction, year: null }

avent_feed_atom:
    path: /avent/{year}/feed.atom
    defaults: { _controller: Afsy\Controller\AventController::feedAction, _format: xml }

avent_day:
    path: /avent/{year}/{slug}
    defaults: { _controller: Afsy\Controller\AventController::dayAction }

admin_redirect:
    path: /admin
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
        path: /admin/dashboard
        permanent: false

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
