homepage:
    pattern:  /
    defaults: { _controller: AfsyFrontBundle:Blog:index }

feed_atom:
    pattern: /feed.atom
    defaults: { _controller: AfsyFrontBundle:Blog:feed }

blog_home:
    pattern: /blog
    defaults: { _controller: AfsyFrontBundle:Blog:index }

blog_show:
    pattern: /blog/{slug}
    defaults: { _controller: AfsyFrontBundle:Blog:show }

blog_preview:
    pattern: /blog/preview/{slug}
    defaults: { _controller: AfsyFrontBundle:Blog:show, preview: true }

blog_show_tag:
    pattern: /blog/tag/{name}
    defaults: { _controller: AfsyFrontBundle:Blog:showTag }

avent_feed_atom:
    pattern: /avent/feed.atom
    defaults: { _controller: AfsyFrontBundle:Avent:feed, _format: xml }

avent:
    pattern: /avent/{year}
    defaults: { _controller: AfsyFrontBundle:Avent:index, year: null }

# for BC
avent_feed_atom_year:
    pattern: /avent/{year}/feed.atom
    defaults: { _controller: AfsyFrontBundle:Avent:feed, _format: xml }

avent_day:
    pattern: /avent/{year}/{slug}
    defaults: { _controller: AfsyFrontBundle:Avent:day }
